services:
  claimflow.api:
    image: ${DOCKER_REGISTRY-}claimflowapi
    build:
      context: .
      dockerfile: ClaimFlow.API/Dockerfile
    #ports:
    # - "5000:8080"
    environment:
      - CLAIMFLOW_DB_PASSWORD=${CLAIMFLOW_DB_PASSWORD}
      - CLAIMFLOW_RABBIT_USER=${CLAIMFLOW_RABBIT_USER}
      - CLAIMFLOW_RABBIT_PASS=${CLAIMFLOW_RABBIT_PASS}
    depends_on:
     - postgres_db
  postgres_db:
    image: postgres:18.4
    container_name: claimflow_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${CLAIMFLOW_DB_PASSWORD}
      POSTGRES_DB: ClaimFlowDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: claimflow_rabbitmq
    ports:
      - "5672:5672"   #amqp port
      - "15672:15672" #web portal
    environment:
      RABBITMQ_DEFAULT_USER: ${CLAIMFLOW_RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${CLAIMFLOW_RABBIT_PASS}
  claimflow.worker:
    image: ${DOCKER_REGISTRY-}claimflowworker
    build:
      context: .
      dockerfile: ClaimFlow.Worker/Dockerfile
    environment:
      - CLAIMFLOW_DB_PASSWORD=${CLAIMFLOW_DB_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - postgres_db
  claimflow-frontend:
    image: claimflow-frontend
    container_name: claimflow_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #ports:
    #  - "5173:5173"
    environment: #api endpoint
      #- VITE_API_URL=http://localhost:5000
      - VITE_API_URL=https://localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - claimflow.api #Vite boots up AFTER the api
  caddy:
    image: caddy:2-alpine
    container_name: claimflow_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - claimflow.api
      - claimflow-frontend
volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  
