name: .NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ClaimFlow.slnx
    - name: Build
      run: dotnet build ClaimFlow.slnx --no-restore --configuration Release 
      
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
      
    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend